#==============================================#
  # Spawn Manager by RedSMURF: Configuration file #
#==============================================#

[Main Settings]
SETTING_DEFAULT_MODEL_T         = models/player/arctic/arctic.mdl
SETTING_DEFAULT_MODEL_CT        = models/player/sas/sas.mdl
SETTING_DEFAULT_SEQUENCE        = 0
SETTING_DEFAULT_FRAMERATE       = 1.0

SETTING_SPAWN_LOAD              = 1             # Whether to load saved Spawn Points data of the current map
SETTING_SPAWN_DEFAULT           = 1             # Whether to allow reading default Spawn Points from the map
SETTING_SPAWN_CHECK             = 20.0          # Maximum selection distance when checking nearby spawn points
SETTING_OFFSET_BASE             = 90.0          # Default forward offset when previewing Spawn Point placement
SETTING_OFFSET                  = 42.0 900.0    # Minimum - Maximum offset from the player to the Spawn Point
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move Spawn Point forward/backward
SETTING_OFFSET_FREQ             = 0.1           # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1           # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 90            # Transparency of the ghost model

SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav
SETTING_COLOR_SELECT            = 0 255 0